### ISSUE TITLE
Use Marlin defaults to prevent false thermal runaway alerts and make them configurable from UI

### ISSUE THREAD

**Issue by bonjipoo** [gdombiak/OctoPrint-OctoPod#114]
Still getting thermal runaway alerts after 0.3.7

**Comment by bonjipoo** [comment]
Hi @gdombiak, Yes I don't get a thermal run away alert when I reprint but I do when I start a print from ambient it seems.  So this morning when I started printing again it threw a thermal runaway notification.  Im printing a lot at the moment so the print may no be reaching low enough temperatures between prints to trigger the alert.  Have had this issue for a week or so.  Hope this helps.

[octoprint-9.log](https://github.com/gdombiak/OctoPrint-OctoPod/files/7070471/octoprint-9.log)

**Comment by gdombiak** [comment]
Thanks @bonjipoo for sharing the logs. I see that after 10 seconds the hotend temperature did not increase by even a 0.01 degree. 

```
2021-08-28 10:19:02,495 - octoprint.plugins.octopod - DEBUG - Thermal runaway - Started to track tool0. Temp should go up. Actual 19.6 and Target 210.0 
2021-08-28 10:19:07,504 - octoprint.plugins.octopod - DEBUG - Thermal runaway - Tracking tool0. Temp NOT going up. Will wait more time. Actual 19.6 and Target 210.0 
2021-08-28 10:19:12,512 - octoprint.plugins.octopod - WARNING - Possible thermal runaway detected for tool0. Actual 19.6 and Target 210.0 
```

Quick workaround until I release a new version. 
1. ssh into OctoPi 
2. open **.octoprint/config.yaml** with an editor (e.g. vi or nano)
3. under **plugins -> octopod** add a new property and set its value **thermal_warmup_seconds_threshold: 19**. In this example it will wait 19 seconds to warm up a bit before sending the thermal runaway alert. Increment by 5 seconds if needed.
4. restart OctoPrint

I guess room temperature is cold since after 10 seconds it did not warm up even a bit. I'm curious, do you have thermal runaway protection in the firmware? 

Regards,
Gaston

**Comment by gdombiak** [comment]
Thanks @bonjipoo for bringing this issue up. I now use Marlin defaults and also made them configurable from UI. Will do a new release now

![Screen Shot 2021-08-28 at 9 47 03 AM](https://user-images.githubusercontent.com/1791267/131224934-ab25217f-b8ae-492b-9d3f-031832c44b37.png)

**Comment by bonjipoo** [comment]
Great thanks,  Just so you know.  My printer in a Voron V0.1 with 6mm thick aluminium heated bed.  That could be why the temperature sensor is slow to read.  The hotend however consists of a E3D thermistor and cartridge in a dragon hotend.  Pretty standard stuff these days.  Tricky for you when everyone has something different in the 3D printer world.  Many Thanks for your prompt work.

**Comment by gdombiak** [comment]
Nice setup @bonjipoo!! New release is out so no need for the manual workaround. Just do an update to 0.3.8 and let me know how it goes. If OctoPrint does not see the update then go here for a force update.
![Screen Shot 2021-08-28 at 10 54 09 AM](https://user-images.githubusercontent.com/1791267/131226662-342fef92-0460-4067-b390-51c510208c58.png)
